global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'triterm-production'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules
rule_files:
  - 'alerts.yml'

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'triterm-server'

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          instance: 'triterm-db'

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          instance: 'triterm-containers'

  # TriTerm Server health endpoint
  - job_name: 'triterm-server'
    metrics_path: '/health'
    static_configs:
      - targets: ['server:3000']
        labels:
          service: 'triterm-server'
          instance: 'server'

  # TriTerm Client health endpoint
  - job_name: 'triterm-client'
    metrics_path: '/health'
    static_configs:
      - targets: ['client:80']
        labels:
          service: 'triterm-client'
          instance: 'client'
